[".tmux/plugins/tpm"]
type="git-repo"
url="https://github.com/tmux-plugins/tpm"
refreshPeriod="1h"

{{ $vegetaVersion := "12.13.0" -}}
[".local/bin/vegeta"]
    type = "archive-file"
    url = "https://github.com/tsenart/vegeta/releases/download/v{{ $vegetaVersion }}/vegeta_{{ $vegetaVersion }}_{{ .chezmoi.os }}_{{ .chezmoi.arch }}.tar.gz"
    path = "vegeta"

[".bash-preexec.sh"]
    type = "file"
    url = "https://raw.githubusercontent.com/rcaloras/bash-preexec/master/bash-preexec.sh"
    refreshPeriod = "168h"

{{ $carapaceVersion := "1.7.3" -}}
[".local/bin/carapace"]
    type = "archive-file"
    url = "https://github.com/carapace-sh/carapace-bin/releases/download/v{{ $carapaceVersion }}/carapace-bin_{{ $carapaceVersion }}_{{ .chezmoi.os }}_{{ .chezmoi.arch }}.tar.gz"
    path = "carapace"

