set-option -g   prefix M-a
bind-key M-a    send-prefix
unbind-key r         ; bind r                source-file ~/.tmux.conf\; display "conf reloaded!"
unbind-key M-l       ; bind-key -n M-l       run-shell "tmux send-keys -R ; tmux clear-history"
unbind-key M-Left    ; bind-key -n M-Left    select-pane -L
unbind-key M-Down    ; bind-key -n M-Down    select-pane -D
unbind-key M-Up      ; bind-key -n M-Up      select-pane -U
unbind-key M-Right   ; bind-key -n M-Right   select-pane -R
unbind-key M-1       ; bind-key -n M-1       select-window -t 1
unbind-key M-2       ; bind-key -n M-2       select-window -t 2
unbind-key M-3       ; bind-key -n M-3       select-window -t 3
unbind-key M-4       ; bind-key -n M-4       select-window -t 4
unbind-key M-5       ; bind-key -n M-5       select-window -t 5
unbind-key M-6       ; bind-key -n M-6       select-window -t 6
unbind-key M-7       ; bind-key -n M-7       select-window -t 7
unbind-key M-8       ; bind-key -n M-8       select-window -t 8
unbind-key M-9       ; bind-key -n M-9       select-window -t 9
unbind-key M-z       ; bind-key -n M-z       resize-pane -Z
unbind-key M--       ; bind-key -n M--       split-window -v
unbind-key M-=       ; bind-key -n M-=       split-window -h
unbind-key M-s       ; bind-key -n M-s       choose-tree -Zs
unbind-key M-h       ; bind-key -n M-h       list-keys -T prefix
unbind-key M-m       ; bind-key -n M-m       set-option -g mouse \; display-message 'Mouse #{?mouse,on,off}'
unbind-key M-x       ; bind-key -n M-x       confirm-before -p "kill window '#W'? (y/n)" kill-window
unbind-key m         ; bind m                command-prompt -p "man:" "new-window -n 'man %1' 'tldr %1' ; set-window-option remain-on-exit on ; split-window -h 'man %1'"
set -g mouse on
set -g base-index 1
set -s escape-time 0
set -g status-interval 5
set -g history-limit 50000
set -g repeat-time 100

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'

set -g @fuzzback-finder-bind 'ctrl-y:execute-silent(echo -n {3..} | xsel -ib)+abort'
set -g @plugin 'roosta/tmux-fuzzback'

# statusbar
set -g @plugin '2kabhishek/tmux2k'
set -g @tmux2k-left-plugins "session"
set -g @tmux2k-session-colors "light_blue black"
set -g @tmux2k-theme 'gruvbox'
set -g @tmux2k-icons-only false
set -g @tmux2k-show-powerline true

# session management
set -g @plugin '2kabhishek/tmux-tea'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @tea-find-path "$HOME/repos"
set -g @tea-alt-bind "false"
set -g @tea-session-name "full-path"
set -g @tea-include-sessions "false"
set -g @tea-eza-options "-ahlT -L=1 -s=extension --group-directories-first --icons --git --git-ignore --no-user --color=always"

run '~/.tmux/plugins/tpm/tpm'
